### ISSUE TITLE
G-means

### ISSUE THREAD

**Issue by nabilEM** [annoviko/pyclustering#506]
Hello,

Thank you for your library, it's just fantastic and very useful.
I saw that G-means a well know clustering method haven't good implementation in python in internet. May you integrate it in your library?

Thank you.

**Comment by annoviko** [comment]
Hello, @nabilElmalki ,

Looks like this algorithm popular, that you for your proposal. I will include this request to backlog for 0.9.1 release.

**Comment by annoviko** [comment]
**Sources**
1. Paper: Zhao Z., Guo S., Xu Q., Ban T. (2009) G-Means: A Clustering Algorithm for Intrusion Detection. In: Köppen M., Kasabov N., Coghill G. (eds) Advances in Neuro-Information Processing. ICONIP 2008. Lecture Notes in Computer Science, vol 5506. Springer, Berlin, Heidelberg

**Sub-tasks**

- [ ] Python implementation of the algorithm.

- [ ] C/C++ implementation of the algorithm and interface for python.

- [ ] Unit and integration tests.

- [ ] Documentation and examples.

**Comment by nabilElmalki** [comment]
Thank you. I look forward to the new version.

**Comment by annoviko** [comment]
The algorithm is available on the branch 'master'. And will be available in the release 0.9.2.
