### ISSUE TITLE
[pyclustering.utils.metric] V-Measure

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#631]
**Introduction**
There is a discussion regarding to purity estimation - see #620 . In order to cover this proposal, V-Measure should be implemented.

**References**
Article: V-Measure: A conditional entropy-based external cluster evaluation measure. Andrew Rosenberg and Julia Hirschberg.

**Description**
The functionality should be implemented for Python and C++ version. The following namespaces are proposed:
- pyclustering.utils.metric (Python).
- pyclustering::utils::metric (C++).

The implementation should be done in line with the description.

**Sub-tasks**

- [ ] Implement V-Measure for Python version of the library.
- [ ] Implement V-Measure for C++ version of the library.
- [ ] Implement integration of the C++ into Python.
- [ ] Write documentation for Python version including examples.
- [ ] Write documentation for C++ version including examples.
