### ISSUE TITLE
[pyclustering.utils.metric][ccore.utils.metric] F-measure

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#632]
**Introduction**
There is a discussion regarding to purity estimation - see #620 . In order to cover this proposal, F-Measure should be implemented.

**References**
Article: The truth of the F-measure. Yutaka Sasaki.

**Sub-tasks**
- [ ] Implement F-Measure for Python version of the library.
- [ ] Implement F-Measure for C++ version of the library.
- [ ] Implement integration of the C++ into Python.
- [ ] Write documentation for Python version including examples.
- [ ] Write documentation for C++ version including examples.
